### PR TITLE
Blazing Fast Column Width Update (with passing tests)

### PR DESCRIPTION
**Pull request by SimplGy**
New method `grid.updateColumnWidths(columnDefinitions)` improves performance *dramatically* when all you need to do is adjust widths. I built it so that the whole grid isn't redrawn, only the styles are updated and the width on the header cells is modified.

Performance on my machine went from `76ms` to `2ms`, so there's a huge gain. Also, because the grid is not re-rendered in this model, all of the custom things folks (heh, me) might add to the column headers don't need to be re-drawn/bound.

I added a passing test for the traditional `setColumns` approach, and a passing test for the new `updateColumnWidths` approach. The test prints timing so you can see for yourself.

I use many of the grid features, but not all of them, so it's possible (likely?) I have missed something and this surgical resize option does not work if that feature is enabled. If so, I'd be happy to add a test case for it and fix it.

In terms of arguing for its broad applicability, I have collected the following evidence. I think this new method would help anyone trying to autofit columns to content (this is my use case, in fact.)

#### Prior requests/discussion/issues:

http://stackoverflow.com/questions/6794656/how-do-i-autosize-the-column-in-slickgrid
https://groups.google.com/forum/#!topic/slickgrid/dYtmwhfFCTw
https://groups.google.com/forum/#!topic/slickgrid/TmvDUzaKfPk
https://github.com/mleibman/SlickGrid/issues/305
http://stackoverflow.com/questions/15200574/slickgrid-column-width-should-automatically-get-resized-according-to-widest-row
https://github.com/mleibman/SlickGrid/issues/568
https://github.com/mleibman/SlickGrid/pull/733
http://stackoverflow.com/questions/12071844/is-it-possible-to-change-width-of-a-column-in-slickgrid-programatically

There's also a little google groups post I made attempting to get your thoughts on the idea:
https://groups.google.com/forum/#!topic/slickgrid/BBB-Qhg7TvU

### CODE REVIEW

**Comment by SimplGy** [comment]
closing, not going to get merged to master, we maintain our own repo

**Comment by 6pac** [comment]
There is an interesting question of maintaining sync between repos. I think we do need separate repos for the major forks (ie. things like pinned columns go beyond the functionality of a plugin), but it would be great if the divergences were clearly mapped in single or multiple commits.
I find that often a PR has a whole bunch of tweaks unrelated to the feature at hand, which makes it very difficult to use.
I have a habit of developing on a private branch and then when ready for release branching the master, rolling logical groups of patches up using diff between two commit points on the private branch, then applying that patch as a single commit or commit for each of a series of logical functional steps. Of course there may be additional commits afterwards for bug fixing, but these are carefully screened so as to be for only that issue.

I know this is a lot of work, but it does allow other branches to have a clearly defined 'feature' commit set to apply.

I've tried to use that philosophy with the 6pac branch. I have a private DataProvider fork I will release soon which is probably similar to pinned columns in that it is major and affects much of the code.
I plan to release a patch or series of patches for that.

Perhaps this approach isn't realistic, but I think it gives other forks the best possible chance of integrating.

**Comment by SimplGy** [comment]
You're right that we aren't being very community-generous about this, @6pac. Our branch has turned in to a sort of company-specific fork. We make no effort to separate reusable features or those with high community interest from the rest.

This is in part because I judged the interest to be pretty limited--there's maybe 50 people at most who still use slickgrid, really want pinned columns, and haven't written their own fork yet.

I'm sorry it's caused you extra work, I really am, but it's not a community project for us/me.

**Comment by 6pac** [comment]
hey no problem, it hasn't caused me more work, but I'm just seeing what the interest is in adopting these practices.
Do you think SlickGrid is on the way out? If so, what's it being replaced with?
My opinion is that the world has forgotten about grids temporarily in their obsession with mobile devices, but that there is still a definite business niche for full size computers and a highly functional grid is an essential part of that. Slickgrid is just simply the best grid I've seen.
So I would say it's on the up and up, but perhaps in a lull right now.

Would love to be proven wrong on that, because I'm making business decisions based on this opinion!

**Comment by SimplGy** [comment]
I thought it was the best last year. Maybe it still is, but there'd be some benefit to picking a well implemented virtualized grid that meant to go with whatever framework your app is on. In my case, I'd reconsider slickgrid VS the new angular grid.

**Comment by mpetkov** [comment]
Did this method, updateColumnWidths, ever get pushed to this repo?  I  am asking because I don't see it in the master branch.

**Comment by 6pac** [comment]
nothing has been pushed to this repo for two years. i haven't got around to evaluating this yet for my repo (current most active update of MLeibman https://github.com/6pac/SlickGrid).
probably not likely i will until i have more commercial success with a product using SlickGrid. Then I'll be able to justify spending time on more complex and time consuming features.

**Pull request closed without merging**
